version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "maintenance"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "maintenance"
